---
stock_config: {
  apple: {
    ticker_symbol: "AAPL",
  },
  kroger: {
    ticker_symbol: "KR",
  },
  marketaxes: {
    ticker_symbol: "MKTX",
  },
  nintendo: {
    ticker_symbol: "NTDOY",
  },
  ishares: {
    ticker_symbol: "IHE",
  },
  uber: {
    ticker_symbol: "UBER",
  },
  alf: {
    ticker_symbol: "ALF",
  },
  Alpha Teknova: {
    ticker_symbol: "TKNO",
  },
  elevation oncology inc.: {
    ticker_symbol: "ELEV",
  },
  GH Research: {
    ticker_symbol: "GHRS"
  },
  Missfresh Limited: {
    ticker_symbol: "MF"
  },
  Confluent: {
    ticker_symbol: "CFLT"
  },
  Doximity: {
    ticker_symbol: "DOCS"
  },
  Full Truck Alliance: {
    ticker_symbol: "YMM"
  },
  Tremor International: {
    ticker_symbol: 'TRMR' 
  },
  Angel Oak Mortgage: {
    ticker_symbol: 'AOMR'
  },
  Monday.com: {
    ticker_symbol: 'MNDY'
  },
  DLocal Limited: {
    ticker_symbol: 'DLO'
  },
  FIGS inc: {
    ticker_symbol: 'FIG'
  },
  Flywire corp: {
    ticker_symbol: 'FLYW'
  },
  Paymentus Holdings: {
    ticker_symbol: 'PAY'
  }
}